export interface GalleryImage {
  src: string;
  alt: string;
}

export const galleryImages: GalleryImage[] = [
  { src: "/assets/gallery/1imagen.jpg", alt: "Evento DreamDrinks 1" },
  { src: "/assets/gallery/2imagen.jpg", alt: "Evento DreamDrinks 2" },
  { src: "/assets/gallery/3imagen.jpg", alt: "Evento DreamDrinks 3" },
  { src: "/assets/gallery/4imagen.jpg", alt: "Evento DreamDrinks 4" },
  { src: "/assets/gallery/5imagen.jpg", alt: "Evento DreamDrinks 5" },
  { src: "/assets/gallery/6imagen.jpg", alt: "Evento DreamDrinks 6" },
  { src: "/assets/gallery/7imagen.jpg", alt: "Evento DreamDrinks 7" },
  { src: "/assets/gallery/8imagen.jpg", alt: "Evento DreamDrinks 8" },
  { src: "/assets/gallery/9imagen.jpg", alt: "Evento DreamDrinks 9" },
  { src: "/assets/gallery/10imagen.jpg", alt: "Evento DreamDrinks 10" },
  { src: "/assets/gallery/11imagen.jpg", alt: "Evento DreamDrinks 11" },
  { src: "/assets/gallery/12imagen.jpg", alt: "Evento DreamDrinks 12" },
  { src: "/assets/gallery/13imagen.jpg", alt: "Evento DreamDrinks 13" },
  { src: "/assets/gallery/14imagen.jpg", alt: "Evento DreamDrinks 14" },
  { src: "/assets/gallery/15imagen.jpg", alt: "Evento DreamDrinks 15" },
  { src: "/assets/gallery/16imagen.jpg", alt: "Evento DreamDrinks 16" },
  { src: "/assets/gallery/17imagen.jpg", alt: "Evento DreamDrinks 17" },
  { src: "/assets/gallery/18imagen.jpg", alt: "Evento DreamDrinks 18" },
  { src: "/assets/gallery/19imagen.jpg", alt: "Evento DreamDrinks 19" },
  { src: "/assets/gallery/20imagen.jpg", alt: "Evento DreamDrinks 20" },
  { src: "/assets/gallery/21imagen.jpg", alt: "Evento DreamDrinks 21" },
  { src: "/assets/gallery/22imagen.jpg", alt: "Evento DreamDrinks 22" },
  { src: "/assets/gallery/23imagen.jpg", alt: "Evento DreamDrinks 23" },
  { src: "/assets/gallery/24imagen.jpg", alt: "Evento DreamDrinks 24" },
  { src: "/assets/gallery/25imagen.jpg", alt: "Evento DreamDrinks 25" },
  { src: "/assets/gallery/26imagen.jpg", alt: "Evento DreamDrinks 26" },
  { src: "/assets/gallery/27imagen.jpg", alt: "Evento DreamDrinks 27" },
  { src: "/assets/gallery/28imagen.jpg", alt: "Evento DreamDrinks 28" },
  { src: "/assets/gallery/29imagen.jpg", alt: "Evento DreamDrinks 29" },
  { src: "/assets/gallery/30imagen.png", alt: "Evento DreamDrinks 30" },
  { src: "/assets/gallery/31imagen.jpg", alt: "Evento DreamDrinks 31" },
  { src: "/assets/gallery/32imagen.jpg", alt: "Evento DreamDrinks 32" },
  { src: "/assets/gallery/33imagen.jpg", alt: "Evento DreamDrinks 33" },
  { src: "/assets/gallery/34imagen.jpg", alt: "Evento DreamDrinks 34" },
  { src: "/assets/gallery/35imagen.jpg", alt: "Evento DreamDrinks 35" },
  { src: "/assets/gallery/36imagen.jpg", alt: "Evento DreamDrinks 36" },
  { src: "/assets/gallery/37imagen.jpg", alt: "Evento DreamDrinks 37" },
  { src: "/assets/gallery/38imagen.jpg", alt: "Evento DreamDrinks 38" },
  { src: "/assets/gallery/39imagen.jpeg", alt: "Evento DreamDrinks 39" },
  { src: "/assets/gallery/40imagen.jpeg", alt: "Evento DreamDrinks 40" },
  { src: "/assets/gallery/41imagen.jpeg", alt: "Evento DreamDrinks 41" },
  { src: "/assets/gallery/42imagen.jpeg", alt: "Evento DreamDrinks 42" },
  { src: "/assets/gallery/43imagen.jpeg", alt: "Evento DreamDrinks 43" },
  { src: "/assets/gallery/44imagen.jpeg", alt: "Evento DreamDrinks 44" },
  { src: "/assets/gallery/45imagen.jpeg", alt: "Evento DreamDrinks 45" },
  { src: "/assets/gallery/46imagen.jpeg", alt: "Evento DreamDrinks 46" },
  { src: "/assets/gallery/47imagen.jpeg", alt: "Evento DreamDrinks 47" },
];
